import { useTheme } from "@react-navigation/native";
import { height, width } from "@utils/helper";
import { StyleSheet } from "react-native";
import { scale } from "react-native-size-matters";
import { useResponsive } from "../../../hooks/useResponsive";

const useStyle = () => {
  const { colors } = useTheme();
  const { hp } = useResponsive();
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    messagesContainer: {
      flex: 1,
    },
    chatScrollView: {
      flex: 1,
    },
    scrollContainer: {
      paddingHorizontal: 0,
      paddingTop: height * 0.01,
      paddingBottom: height * 0.01,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: height * 0.025,
      paddingHorizontal: width * 0.02,
      borderBottomWidth: 1,
      borderColor: colors.border || colors.lightGray,
      backgroundColor: colors.card || colors.background,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    backIcon: {
      marginRight: width * 0.04,
      width: scale(18),
      height: scale(18),
      tintColor: colors.text,
    },
    headerImage: {
      width: width * 0.12,
      height: width * 0.12,
      borderRadius: width * 0.06,
      marginRight: width * 0.04,
    },
    headerPlaceholder: {
      width: width * 0.12,
      height: width * 0.12,
      borderRadius: 50,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      marginRight: width * 0.04,
    },
    headerPlaceholderText: {
      fontSize: scale(18),
      color: colors.background,
      fontWeight: "bold",
    },
    headerTextContainer: {
      flex: 1,
    },
    headerName: {
      fontSize: scale(16),
      fontWeight: "600",
      color: colors.text,
    },
    headerStatus: {
      fontSize: scale(12),
      color: colors.gray,
      marginTop: hp(0.2),
    },
    button: {
      backgroundColor: colors.primary,
      paddingVertical: height * 0.015,
      paddingHorizontal: width * 0.06,
      borderRadius: height * 0.03,
    },
    buttonText: {
      color: "#FFFFFF",
      fontSize: scale(14),
    },
    buttonOutline: {
      borderColor: colors.primary,
      borderWidth: 1,
      paddingVertical: height * 0.015,
      paddingHorizontal: width * 0.06,
      borderRadius: height * 0.03,
    },
    buttonOutlineText: {
      color: colors.primary,
      fontSize: scale(14),
    },
    chatArea: {
      flex: 1,
      borderWidth: 1,
    },
    messageBubble: {
      padding: height * 0.015,
      marginVertical: height * 0.01,
      marginHorizontal: width * 0.02,
      maxWidth: "80%",
      borderRadius: scale(12),
    },
    myMessage: {
      alignSelf: "flex-end",
      backgroundColor: colors.primary,
    },
    theirMessage: {
      alignSelf: "flex-start",
      backgroundColor: colors.card || colors.lightGray,
    },
    messageText: {
      fontSize: scale(14),
      marginRight: 50,
      color: colors.text,
    },
    inputContainer: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: width * 0.02,
      paddingVertical: height * 0.015,
      borderTopWidth: 1,
      borderColor: colors.border || colors.lightGray,
      backgroundColor: colors.card || colors.background,
      minHeight: height * 0.07,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: -1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    textInput: {
      flex: 1,
      paddingHorizontal: width * 0.03,
      paddingVertical: height * 0.01,
      fontSize: scale(14),
      color: colors.text,
      borderWidth: 1,
      borderColor: colors.border || colors.lightGray,
      borderRadius: height * 0.025,
      backgroundColor: colors.background,
      maxHeight: height * 0.12,
      marginRight: width * 0.02,
    },
    textInputContainer: {
      flex: 1,
      marginRight: width * 0.02,
    },
    sendIcon: {
      width: height * 0.025,
      height: height * 0.025,
      resizeMode: "contain",
      tintColor: "#FFFFFF",
    },
    sendButton: {
      backgroundColor: colors.primary,
      paddingHorizontal: width * 0.04,
      paddingVertical: height * 0.015,
      borderRadius: height * 0.025,
      justifyContent: "center",
      alignItems: "center",
    },
    card: {
      backgroundColor: colors.background,
      borderRadius: height * 0.02,
      alignItems: "center",
      justifyContent: "center",
      padding: height * 0.025,
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      height: height * 0.4,
      width: width * 0.8,
      alignSelf: "center",
      borderWidth: 1,
      borderColor: colors.border || colors.lightGray,
    },
    profileContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: height * 0.015,
    },
    cardImage: {
      width: width * 0.15,
      height: width * 0.15,
      borderRadius: width * 0.075,
      marginRight: width * 0.04,
    },
    cardPlaceholder: {
      width: width * 0.15,
      height: width * 0.15,
      borderRadius: width * 0.075,
      backgroundColor: colors.lightyellow,
      justifyContent: "center",
      alignItems: "center",
      marginRight: width * 0.04,
    },
    cardPlaceholderText: {
      fontSize: scale(22),
      color: colors.primary,
      fontWeight: "bold",
    },
    cardTitle: {
      fontSize: scale(24),
      marginBottom: height * 0.005,
      color: colors.text,
      fontWeight: "bold",
    },
    actionButton: {
      marginTop: height * 0.01,
    },
    cardDescription: {
      fontSize: scale(14),
      color: colors.gray,
    },
    actionRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: height * 0.02,
      gap: width * 0.04,
    },
    profileImage: {
      height: height * 0.08,
      width: height * 0.06,
      resizeMode: "contain",
      borderRadius: height * 0.0325,
    },
    cardPlaceholderCentered: {
      width: width * 0.2,
      height: width * 0.2,
      borderRadius: width * 0.1,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: height * 0.02,
      alignSelf: "center",
    },
    cardDescriptionCentered: {
      fontSize: scale(13),
      color: colors.text,
      textAlign: "center",
      marginTop: height * 0.005,
    },
    actionRowCentered: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginTop: height * 0.02,
      gap: width * 0.04,
      flexWrap: "wrap",
    },
    usenotfoud: {
      color: "#FF0000",
      fontSize: scale(20),
      textAlign: "center",
    },
    renderFriendStatusCard: {
      alignItems: "center",
      justifyContent: "center",
      flexGrow: 1,
    },
    nomessages: {
      textAlign: "center",
      marginTop: 10,
    },
    chatImage: {
      width: height * 0.2,
      height: height * 0.2,
      borderRadius: 10,
    },
    modalImage: {
      width: "100%",
      height: height * 0.4,
    },
    chatVideo: {
      width: height * 0.2,
      height: height * 0.2,
      borderRadius: 8,
      backgroundColor: colors.background,
    },
    modalVideo: {
      width: "100%",
      height: height * 0.3,
      backgroundColor: colors.background,
      borderRadius: 8,
    },
    playIconOverlay: {
      position: "absolute",
      top: "40%",
      left: "40%",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.6)",
      width: height * 0.04,
      height: height * 0.04,
      borderRadius: height * 0.02,
    },
    playBtn: {
      width: height * 0.025,
      height: height * 0.025,
      tintColor: "#FFFFFF",
    },
    menuIcon: {
      width: height * 0.025,
      height: height * 0.025,
      tintColor: colors.text,
    },
    menuContainer: {
      position: "absolute",
      top: scale(55),
      right: scale(20),
      backgroundColor: colors.background,
      borderRadius: scale(10),
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 5,
    },
    themeGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      padding: 10,
    },
    themeOption: {
      width: "48%",
      aspectRatio: 2 / 3,
      marginBottom: height * 0.02,
      borderRadius: 8,
      overflow: "hidden",
      backgroundColor: colors.background,
    },
    themeImage: {
      width: "100%",
      height: "100%",
    },
    padding: {
      padding: scale(10),
    },
    flex: {
      flex: 1,
    },
    flexGrow: {
      flexGrow: 1,
    },
    menuText: {
      color: colors.primary,
    },
    map: {
      width,
      height,
    },
    bottomSheet: {
      paddingTop: 12,
      paddingBottom: height * 0.02,
      paddingHorizontal: height * 0.02,
      backgroundColor: colors.background,
      borderTopLeftRadius: height * 0.02,
      borderTopRightRadius: height * 0.02,
      shadowColor: colors.text,
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 8,
    },
    bottomSheetHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: height * 0.01,
    },
    bottomSheetTitle: {
      fontSize: scale(16),
      color: colors.text,
      fontWeight: "600",
    },
    durationChips: {
      flexDirection: "row",
      gap: 8,
    },
    durationChip: {
      paddingHorizontal: height * 0.01,
      paddingVertical: 6,
      borderRadius: height * 0.02,
      borderWidth: 1,
      backgroundColor: "transparent",
      borderColor: colors.primary,
    },
    durationChipSelected: {
      backgroundColor: colors.primary,
    },
    durationChipText: {
      fontSize: scale(12),
      color: colors.text,
    },
    durationChipTextSelected: {
      color: "#FFFFFF",
    },
    buttonGroup: {
      gap: height * 0.01,
    },
    promptText: {
      marginBottom: height * 0.01,
      color: colors.text,
      fontSize: scale(14),
    },
    mapView: {
      height: height * 0.2,
      width: height * 0.25,
      alignSelf: "center",
      borderRadius: 8,
    },
    stoplivebutton: {
      paddingVertical: 7,
      paddingHorizontal: height * 0.02,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 10,
      backgroundColor: colors.primary,
    },
    menuItemDanger: {
      color: "#FF0000",
    },
    selecteddMessageContainer: {
      backgroundColor: colors.card || colors.lightGray,
      marginTop: 5,
      flexDirection: "row",
      alignItems: "center",
      padding: 10,
      justifyContent: "space-between",
    },
    selecteddMessageview: {
      flexDirection: "row",
      alignItems: "center",
    },
    pinnedMessageIcon: {
      width: height * 0.02,
      height: height * 0.02,
      tintColor: colors.text,
      marginRight: 8,
    },
    selectedMessageIcon: {
      width: height * 0.02,
      height: height * 0.02,
      tintColor: colors.primary,
      marginRight: 8,
    },
    selecteddMessageText: {
      color: colors.primary,
      fontWeight: "500",
    },
    pinnedMsgText: {
      color: colors.text,
      fontSize: scale(14),
      flex: 1,
    },
    pinnedMessageContainer: {
      backgroundColor: colors.card || colors.lightGray,
      padding: height * 0.015,
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
    },
    selectedItem: {
      backgroundColor: colors.lightyellow,
      elevation: 2,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    editedtext: {
      fontSize: scale(10),
      color: colors.gray,
      marginTop: 1,
      fontStyle: "italic",
    },
    timeContainer: {
      marginTop: 4,
      position: "absolute",
      right: 10,
      bottom: 3,
    },
    timeText: {
      fontSize: scale(11),
      color: colors.gray,
    },
    dateLabelContainer: {
      alignSelf: "center",
      marginVertical: 10,
      backgroundColor: colors.lightGray,
      borderRadius: 10,
      paddingHorizontal: 15,
      paddingVertical: 7,
    },
    dateLabelText: {
      fontSize: scale(12),
      color: colors.text,
      fontWeight: "600",
    },
  });
};

export { useStyle as default };
